### ISSUE TITLE
Create a detailed design document, with real code samples and an implementation plan.

### ISSUE THREAD

**Issue by danielscholl** [danielscholl-osdu/osdu-developer#3]
Using the following information create a detailed design document with real code samples on how this could be integrated into the osdu-developer-base chart. In a markdown file.  Ensure to include the required Istio Versions necessary for the solution.

**Specification: Integrating MISE Validation into Istio-based JWT Workflow**

---

### Overview

This design outlines the integration of the Microsoft Identity Secure Enclave (MISE) validation container into an existing Istio-based service mesh where JWT validation is already performed using Istio's `RequestAuthentication` and token claim extraction is handled using a Lua-based `EnvoyFilter`.

The goal is to enforce MISE-based token validation as an additional gate using Istio's `CUSTOM` AuthorizationPolicy action, leveraging the Envoy external authorization (`ext_authz`) filter.

---

### Objectives

* Enforce an additional layer of token validation via MISE container.
* Preserve existing Istio-based JWT signature validation and Lua-based header injection.
* Maintain modularity and compatibility with existing Helm charts and Kubernetes YAML structure.
* Use native Istio mechanisms (no sidecar or additional components needed).

---

#### Current Flow:

```mermaid
graph TD
  A[Client Request] --> B[Istio Ingress Gateway or Sidecar]
  B --> C[Istio RequestAuthentication: JWT Signature Check]
  C --> D[Envoy Lua Filter: Extract Claims, Inject Headers]
  D --> E[Forward to Application]
```

#### Target Flow (with MISE):

```mermaid
graph TD
  A[Client Request] --> B[Istio Ingress Gateway or Sidecar]
  B --> C[Istio RequestAuthentication: JWT Signature Check]
  C --> D[Envoy Lua Filter: Inject x-user-id, x-app-id]
  D --> E[Istio ext_authz: Call MISE /ValidateRequest]
  E -->|200 OK| F[Forward to Application]
  E -->|401/403| G[Reject Request]
```

---

#### 1. **MISE Deployment and Service**

A Kubernetes Deployment and Service to run the MISE validation container within the cluster.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mise
  template:
    metadata:
      labels:
        app: mise
    spec:
      containers:
      - name: mise
        image: <your-mise-image>
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mise
spec:
  selector:
    app: mise
  ports:
  - port: 5000
```

#### 2. **Istio MeshConfig Extension Provider**

Add MISE as an external authorization provider. Recommended to apply via IstioOperator configuration.

```yaml
meshConfig:
  extensionProviders:
    - name: mise
      envoyExtAuthzHttp:
        service: mise.default.svc.cluster.local
        port: 5000
        includeHeadersInCheck:
          - authorization
          - x-forwarded-for
          - original-uri
          - original-method
        headersToUpstreamOnAllow:
          - x-user-id
          - x-app-id
        statusOnError:
          code: 403
```

> Note: If modifying meshConfig is not feasible, an equivalent `EnvoyFilter` can be manually defined to insert the ext\_authz filter.

#### 3. **AuthorizationPolicy with CUSTOM Action**

Defines that the selected workload must call MISE for every inbound request.

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-mise-validation
  namespace: <your-namespace>
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: <your-app-label>
  action: CUSTOM
  provider:
    name: mise
  rules:
    - to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
```

---

### Helm Chart Integration

* **Create `templates/mise-deployment.yaml`** for the Deployment + Service block.
* **Create `templates/mise-authz-policy.yaml`** for the AuthorizationPolicy.
* Include MISE-related values in `values.yaml` (e.g. `mise.enabled`, `mise.image`).
* Use conditionals (`{{- if .Values.mise.enabled }}`) to toggle MISE integration.

---

### Testing and Verification

1. Apply the updated Helm chart.
2. Send a request with a valid JWT to your app service.
3. Confirm:

   * MISE receives a request at `/ValidateRequest`.
   * Request only proceeds if MISE returns 200.
   * Otherwise, a `401 Unauthorized` or `403 Forbidden` is returned.

---

### Benefits

* Full compatibility with existing Istio authentication model.
* Maintains separation of concerns: Istio handles signature validation and routing; MISE handles policy enforcement.
* Easy to test, disable, or replace.

---

### Future Enhancements

* Inject claims returned by MISE back into headers.
* Add caching to MISE for repeated validation.
* Extend Lua filter to read from MISE headers if enriched.

---

### Appendix

**Relevant Existing Files:**

* `templates/request-authentication.yaml`: Already in place for JWT validation.
* `templates/envoy-filter.yaml`: Lua logic for token decoding and header injection.

**New/Modified Files:**

* `templates/mise-deployment.yaml`
* `templates/mise-authz-policy.yaml`
* Optionally, Istio `meshConfig` or `EnvoyFilter` for `ext_authz`
